name: ctok
type: controlled
vocab_size: 16000
base_charset: byte
min_freq: 2
min_len: 2
max_len: 8
lambda_weight: 0.0
boundary_aware: false
special_tokens:
  cls: "<s>"
  sep: "</s>"
  pad: "<pad>"
  unk: "<unk>"
  mask: "<mask>"
