dataset: logfit-project/HDFS_v1
config: ""
split: train
text_key: ""
label_key: ""
tokenizer_name: ""
tokenizer_root: tokenizers
outdir: ""
corpus_out: ""
write_corpus: false
force_corpus: false
corpus_num_proc: 0
max_samples: 0
num_workers: 0
mp_chunksize: 16
mp_chunk_factor: 1
mp_chunk_chars: 0
candidate_prefilter_samples: 0
candidate_prefilter_min_freq: 1
streaming: false
preview: 3
sample_ratio: 1.0
seed: 42
cache_dir: datasets/hf_cache
no_hygiene: false
no_filter_value_fragments: false
min_doc_freq: 1
max_doc_concentration: 1.0
junk_penalty_beta: 0.5
pretokenizer: generic
lowercase: false
vocab_size: 8192
max_len: 12
min_freq: 50
max_chars_per_sample: 4096
boundaries: "=&?:/\\n\\t <>\\\"'"
no_boundary_ends: false
max_base_chars: 4096
semantic_mode: none
lambda_sem: 0.0
semantic_top_k: 50000
model_max_length: 512
use_ascii_base: false
base_chars_max_samples: 200000
emit_code: false
hydra:
  run:
    dir: .
  job:
    chdir: false
