name: waf_http
task: binary_classification
input_type: request
format: hf
hf_dataset: puyang2025/waf_data_v2
hf_split: train
text_fields: [method, url, protocol, headers, body]
field_delimiter: "\n"
label_field: label
label_mapping:
  normal: 0
  anomalous: 1
